/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZvHH4D7WSWS
 */
import {
  SelectValue,
  SelectTrigger,
  SelectLabel,
  SelectItem,
  SelectGroup,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";

export function ActionsHeader() {
  return (
    <div className="flex items-center space-x-4">
      <h1 className="text-3xl font-semibold">Auctions</h1>
      <div className="grid grid-cols-4 gap-4">
        <Select>
          <SelectTrigger>
            <SelectValue placeholder="Year" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Years</SelectLabel>
              <SelectItem value="2017">2017</SelectItem>
              <SelectItem value="2018">2018</SelectItem>
              <SelectItem value="2019">2019</SelectItem>
              <SelectItem value="2020">2020</SelectItem>
              <SelectItem value="2021">2021</SelectItem>
              <SelectItem value="2022">2022</SelectItem>
              <SelectItem value="2023">2023</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
        <Select>
          <SelectTrigger>
            <SelectValue placeholder="Transmission" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Transmission</SelectLabel>
              <SelectItem value="automatic">Automatic</SelectItem>
              <SelectItem value="manual">Manual</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
        <Select>
          <SelectTrigger>
            <SelectValue placeholder="Body Style" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Body Style</SelectLabel>
              <SelectItem value="coupe">Coupe</SelectItem>
              <SelectItem value="sedan">Sedan</SelectItem>
              <SelectItem value="suv">SUV</SelectItem>
              <SelectItem value="truck">Truck</SelectItem>
              <SelectItem value="convertible">Convertible</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
      </div>
      <div className="flex space-x-4">
        <Button className="text-sm" variant="link">
          Ending soon
        </Button>
        <Button className="text-sm" variant="link">
          Newly listed
        </Button>
        <Button className="text-sm" variant="link">
          Exclusive
        </Button>
        <Button className="text-sm" variant="link">
          No reserve
        </Button>
      </div>
    </div>
  );
}
