/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lXSlZCBBrz3
 */
"use client";

import { Button } from "@/components/ui/button";
import { TrackBidViaWA, TrackGetEarlyAccessClick } from "@/lib/services/pixels";
import { ICar } from "@/lib/types";
import { useState } from "react";
import PhoneInput from "react-phone-input-2";

import "react-phone-input-2/lib/material.css";

// icons
import { FaWhatsapp } from "react-icons/fa";
import InterestedButton from "./interested-button";

export function BidSection({
  carDetail,
  utms,
}: {
  carDetail: ICar;
  utms: any;
}) {
  const [phone, setPhone] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [sent, setSent] = useState(false);

  const { auction, status, title, year } = carDetail;

  let utm_string = "?";

  for (const key in utms) {
    if (Object.prototype.hasOwnProperty.call(utms, key)) {
      const value = utms[key];
      utm_string += `${key}=${value}&`;
    }
  }

  // Remove the last '&' character
  utm_string = utm_string.slice(0, -1);

  async function onSubmitHandler(e: any) {
    e.preventDefault();

    setError("");
    setLoading(true);

    if (!auction) {
      setError("This car is not currently in an auction. Contact us for help.");
      setLoading(false);
      return;
    }

    TrackBidViaWA(phone);

    const url_request = `https://nolemons2.onrender.com/auction-following/${utm_string}`;

    const res = await fetch(url_request, {
      method: "POST",
      body: JSON.stringify({
        phone,
        auction_id: auction?.id,
      }),
    });
    if (res.ok) {
      setSent(true);
    } else {
      setError(
        "Please enter your Whatsapp number to submit a bid or follow the auction."
      );
    }

    setLoading(false);
  }

  const onEarlyAccessClick = () => {
    const text = encodeURIComponent(
      `Hello! I'm interested in ${title} ${year}`
    );
    TrackGetEarlyAccessClick();
    window.open(
      `https://api.whatsapp.com/send/?phone=971566633668&text=${text}`,
      "_blank"
    );
  };

  const createdOrUnverfied = status == "created" || status == "unverified";

  return (
    <section
      className="w-full md:pt-24 lg:pt-32 pb-60 md:h-full "
      id="bid-section"
    >
      <div className="h-1 bg-gray-500 bg-opacity-40 w-9/12 my-12 md:mb-12 mx-auto" />
      <div className="container flex flex-col items-center justify-center gap-4 px-4 text-center md:px-6">
        {createdOrUnverfied ? (
          <>
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
              Get early access
            </h2>
            <p className="mx-auto max-w-[600px] text-zinc-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed ">
              Contact us to get early access to this car.
            </p>
            <Button
              onClick={onEarlyAccessClick}
              className="w-48 flex space-x-1"
            >
              <FaWhatsapp className=" text-lg" />
              <p>Get early access</p>
            </Button>
          </>
        ) : null}

        {status == "for_sale" && (
          <div className=" hidden md:block">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight mb-4">
              Want to buy this car?
            </h2>
            <InterestedButton carDetail={carDetail} />
          </div>
        )}
        {status == "sold" && (
          <>
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
              Looking for a similar car?
            </h2>
            <p className="mx-auto max-w-[600px] text-zinc-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-zinc-400">
              Get in touch with our team and we&apos;ll see if we can help.
            </p>

            <Button
              onClick={onEarlyAccessClick}
              className="w-48 flex space-x-1"
            >
              <FaWhatsapp className=" text-lg" />
              <p>Contact us</p>
            </Button>
          </>
        )}
        {status == "live" &&
          (!sent ? (
            <>
              <div className="space-y-3">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                  Make an Offer
                </h2>
                <p className="mx-auto max-w-[600px] text-zinc-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-zinc-400">
                  Enter your WhatsApp number to submit an offer
                </p>
              </div>
              <div>
                <form onSubmit={onSubmitHandler}>
                  <PhoneInput
                    buttonStyle={{
                      textAlign: "left",
                    }}
                    preferredCountries={["sa", "ae", "qa", "kw", "bh", "om"]}
                    country={"ae"}
                    value={phone}
                    onChange={setPhone}
                  />
                  <Button className=" mt-5" type="submit" disabled={loading}>
                    {loading && (
                      <svg
                        width="20"
                        height="20"
                        fill="currentColor"
                        className="mr-2 animate-spin"
                        viewBox="0 0 1792 1792"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path d="M526 1394q0 53-37.5 90.5t-90.5 37.5q-52 0-90-38t-38-90q0-53 37.5-90.5t90.5-37.5 90.5 37.5 37.5 90.5zm498 206q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-704-704q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm1202 498q0 52-38 90t-90 38q-53 0-90.5-37.5t-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-964-996q0 66-47 113t-113 47-113-47-47-113 47-113 113-47 113 47 47 113zm1170 498q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-640-704q0 80-56 136t-136 56-136-56-56-136 56-136 136-56 136 56 56 136zm530 206q0 93-66 158.5t-158 65.5q-93 0-158.5-65.5t-65.5-158.5q0-92 65.5-158t158.5-66q92 0 158 66t66 158z"></path>
                      </svg>
                    )}
                    Continue on WhatsApp{" "}
                  </Button>
                </form>
              </div>
            </>
          ) : (
            <>
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Thank you!
              </h2>
              <p className="mx-auto max-w-[600px] text-zinc-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-zinc-400">
                You will now receive a message on WhatsApp to submit your offer
                at this number:{" "}
                <span className="font-semibold text-black">+{phone}</span>
              </p>
            </>
          ))}
        {error && <div className="text-red-500">{error}</div>}
      </div>
    </section>
  );
}
