/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lXSlZCBBrz3
 */
"use client";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useState } from "react";

export function BidSection() {
  const [phone, setPhone] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [sent, setSent] = useState(false);

  const onSubmit = async () => {
    setLoading(true);
    const res = await fetch("https://nolemons2.onrender.com/bot/webhook/", {
      method: "POST",
      body: JSON.stringify({
        phone,
        message: `I want to bid on the NFT: ${window.location.href}`,
      }),
    });

    if (res.ok) {
      setSent(true);
    } else {
      setError("Something went wrong. Please try again later.");
    }

    setLoading(false);
  };

  const handleChange = (event: any) => {
    const value = event.target.value;
    // Ensure the input always starts with '+'
    if (value.match(/^\+?/)) {
      setPhone("+" + value.replace(/[^\d]/g, ""));
    }
  };

  return (
    <section className="w-full py-12 md:py-24 lg:py-32" id="bid-section">
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
        {!sent ? (
          <>
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Place a Bid Now
              </h2>
              <p className="mx-auto max-w-[600px] text-zinc-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-zinc-400">
                Enter your phone number and we&apos;ll contact you on WhatsApp
                to confirm your bid.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form
                className="flex flex-col items-center space-y-2"
                onSubmit={(e) => {
                  e.preventDefault();
                  onSubmit();
                }}
              >
                <Input
                  className="max-w-lg flex-1"
                  placeholder="Enter your phone number"
                  type="tel"
                  value={phone}
                  onChange={handleChange}
                />
                <Button type="submit" disabled={loading}>
                  {loading && (
                    <svg
                      width="20"
                      height="20"
                      fill="currentColor"
                      className="mr-2 animate-spin"
                      viewBox="0 0 1792 1792"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M526 1394q0 53-37.5 90.5t-90.5 37.5q-52 0-90-38t-38-90q0-53 37.5-90.5t90.5-37.5 90.5 37.5 37.5 90.5zm498 206q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-704-704q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm1202 498q0 52-38 90t-90 38q-53 0-90.5-37.5t-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-964-996q0 66-47 113t-113 47-113-47-47-113 47-113 113-47 113 47 47 113zm1170 498q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-640-704q0 80-56 136t-136 56-136-56-56-136 56-136 136-56 136 56 56 136zm530 206q0 93-66 158.5t-158 65.5q-93 0-158.5-65.5t-65.5-158.5q0-92 65.5-158t158.5-66q92 0 158 66t66 158z"></path>
                    </svg>
                  )}
                  Bid on WhatsApp{" "}
                </Button>
              </form>
            </div>
          </>
        ) : (
          <>
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
              Thank you!
            </h2>
            <p className="mx-auto max-w-[600px] text-zinc-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-zinc-400">
              We&apos;ll contact you on WhatsApp to confirm your bid.
            </p>
          </>
        )}
        {error && <div className="text-red-500">{error}</div>}
      </div>
    </section>
  );
}
