"use client";
import { useWindowSize } from "@uidotdev/usehooks";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PS6Xy6PWdOo
 */
import { useTranslations } from "next-intl";
import Image from "next/image";
import DropDownMenu from "./DropDownMenu";
import Link from "next/link";
import { usePathname } from "next/navigation";

export function Navbar() {
  const { width } = useWindowSize();
  const t = useTranslations("default.navigation");

  // Get the pathname to make the button in the navbar that matches the current page active.
  const pathname = usePathname();
  const curPathname = pathname.split("/").slice(2).at(0) ?? "";

  return (
    <nav className="sticky top-0 z-[11] flex items-center justify-between  py-4 bg-white  shadow">
      <div className=" container m-auto flex items-center w-full px-4 md:px-16">
        <Link href="/">
          <Image
            className="w-24"
            src="/logo.png"
            width={1500}
            height={238}
            alt="logo"
            priority
          />
        </Link>
        {width! > 1280 ? (
          <div className="flex items-center space-x-4">
            <div className="border-l border-gray-300 h-5 mx-4" />
            <div className="flex items-center space-x-4">
              <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="https://nolemons.ae/p/about-us-2"
              >
                {t("about_us")}
              </a>
              <Link
                className={`text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1 ${
                  curPathname == "how-it-works" ? "bg-gray-200" : ""
                }`}
                href="/how-it-works"
              >
                {t("how_it_works")}
              </Link>
              <Link
                className={`text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1 ${
                  curPathname == "sell-your-car" ? "bg-gray-200" : ""
                }`}
                href="/sell-your-car"
              >
                {t("sell_your_car")}
              </Link>
              <Link
                className={`text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1 ${
                  curPathname == "request-a-car" ? "bg-gray-200" : ""
                }`}
                href="/request-a-car"
              >
                Request a car
              </Link>
              <Link
                className={`text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1 ${
                  curPathname == "why-us" ? "bg-gray-200" : ""
                }`}
                href="/why-us"
              >
                Why us?
              </Link>
              <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="https://nolemons.ae/p/buyer-guide-local"
              >
                UAE buyer guide
              </a>
              <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="https://nolemons.ae/p/buyer-guide"
              >
                International buyer guide
              </a>
            </div>
          </div>
        ) : (
          <DropDownMenu
            items={[
              { label: "About us", link: "https://nolemons.ae/p/about-us-2" },
              { label: "How it works?", link: "/how-it-works" },
              { label: "Sell your car", link: "/sell-your-car" },
              { label: "Request a car", link: "/request-a-car" },
              { label: "Why us?", link: "/why-us" },
              {
                label: "UAE buyer guide",
                link: "https://nolemons.ae/p/buyer-guide-local",
              },
              {
                label: "International buyer guide",
                link: "https://nolemons.ae/p/buyer-guide",
              },
            ]}
            withBackground={false}
            className="ml-auto"
          />
        )}
      </div>
    </nav>
  );
}
