"use client";
import { useWindowSize } from "@uidotdev/usehooks";
import { ExternalLinkIcon, InfoCircledIcon } from "@radix-ui/react-icons";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PS6Xy6PWdOo
 */
import { useTranslations } from "next-intl";
import Image from "next/image";
import DropDownMenu from "./DropDownMenu";

export function Navbar() {
  const { width } = useWindowSize();
  const t = useTranslations("default.navigation");
  return (
    <nav className="sticky top-0 z-[11] flex items-center justify-between px-4 md:px-16 py-4 bg-white  shadow">
      <div className="flex items-center w-full">
        <a href="/">
          <Image src="/logo.png" width={90} height={16} alt="logo" />
        </a>
        {width! > 640 ? (
          <div className="flex items-center space-x-4">
            <div className="border-l border-gray-300 h-5 mx-4" />
            <div className="flex items-center space-x-4">
              {/* <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="https://nolemons.co/p/about-us-2"
              >
                {t("about_us")}
              </a>
              <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="/how-it-works"
              >
                {t("how_it_works")}
              </a> */}
              <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="/sell-your-car"
              >
                {t("sell_your_car")} 
              </a>
              <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="/request-a-car"
              >
                Request a car
              </a>
              <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="https://nolemons.ae/" target="_blank" rel="noopener noreferrer"
              >
                Help center
                <ExternalLinkIcon className="w-4 h-4 inline-block ml-1" />
              </a>
              {/* <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="/why-us"
              >
                Why us?
              </a>
              <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="https://nolemons.co/p/buyer-guide-local"
              >
                UAE buyer guide
              </a>
              <a
                className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
                href="https://nolemons.co/p/buyer-guide"
              >
                International buyer guide
              </a>  */}
            </div>
          </div>
        ) : (
          <DropDownMenu
            items={[
              // { label: "About us", link: "https://nolemons.co/p/about-us-2" },
              // { label: "How it works?", link: "/how-it-works" },
              { label: "Sell your car", link: "/sell-your-car" },
              { label: "Request a car", link: "/request-a-car" },
              { label: "Help center", link: "https://nolemons.ae/" },
              // { label: "Why us?", link: "/why-us" },
              // { label: "UAE buyer guide", link: "https://nolemons.co/p/buyer-guide-local" },
              // { label: "International buyer guide", link: "https://nolemons.co/p/buyer-guide" },
            ]}
            withBackground={false}
            className="ml-auto"
          />
        )}
      </div>
    </nav>
  );
}
