/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PS6Xy6PWdOo
 */
import { Button } from "@/components/ui/button";

export function Navbar() {
  return (
    <nav className="flex items-center justify-between px-6 py-4 bg-white  shadow">
      <div className="flex items-center space-x-4">
        <span className="font-bold text-lg md:text-xl">Nolemons</span>
        <div className="border-l border-gray-300 h-5 mx-4" />
        <div className="flex items-center space-x-4">
          <a
            className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
            href="#"
          >
            Auctions
          </a>
          <a
            className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1 bg-green-200 "
            href="#"
          >
            Sell a car
          </a>
          <a
            className="text-sm md:text-base text-gray-700  hover:bg-gray-200  rounded-md px-2 py-1"
            href="#"
          >
            Help
          </a>
        </div>
      </div>
      <div className="flex items-center space-x-4">
        <input
          aria-label="Search"
          className="px-3 py-2 border border-gray-300 rounded-md text-sm md:text-base hover:bg-gray-200 "
          placeholder="Search..."
          type="search"
        />
        <Button className="hover:bg-gray-200 " variant="outline">
          Sign Up
        </Button>
      </div>
    </nav>
  );
}
